telegram:
  token: "8599751581:AAGaelfUnEhaGtb0xQ7_Uxcw4sTZpFASyd8"
  admin_id: "1917057396"

account:
  login: "СУРАПБЕРГЕНОВ АМИР"
  password: "1Qaz2wsx!"
  sign_password: "1Qaz2wsx!" # Пароль от ключа

target:
  url: "https://v3bl.goszakup.gov.kz/ru/user/login"
  lot_url: "https://v3bl.goszakup.gov.kz/ru/application/docs/15701274/67761206"

paths:
  # Имя файла ключа (оно одинаковое и там, и там)
  key_filename: "GOST512_030b1d6047860ccbb5ec0a1a4af9f6c0ccbf72a6.p12"
  # Путь внутри Докера
  docker_dir: "/goszakup/data"
  # Путь на Windows (Локально)
  local_dir: "d:/goszakup/data"

services:
  ncanode_docker: "http://ncanode:14579"
  ncanode_local: "http://localhost:14579"

data:
  cooks:
    - name: "Иванов Иван"
      diploma_number: "NO12345"
      file_path: "data/test/diploma_1.pdf"
    - name: "Петров Петр"
      diploma_number: "NO67890"
      file_path: "data/test/diploma_2.pdf"