version: '3.8'

services:
  bot:
    build: .
    container_name: gov_bot
    volumes:
      - .:/goszakup
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ncanode

  ncanode:
    build: ./ncanode
    container_name: ncanode
    restart: always
    ports:
      - "14579:14579"
